name: Selenium Tests

on:
  schedule:
    - cron: "0 13 * * *"
  pull_request:
    types: [labeled, opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  run:
    name: Selenium Browser Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'run-selenium')
    strategy:
      matrix:
        python-version: ["3.9", "3.13"]
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v6

    - name: Setup Micromamba env
      uses: mamba-org/setup-micromamba@v3
      with:
        environment-name: TEST
        create-args: >-
          python=3
          --file requirements.txt
          --file requirements-dev.txt

    - name: Install folium from source
      run: python -m pip install -e . --no-deps --force-reinstall

    - name: Install selenium and pillow
      run: pip install selenium pillow

    - name: Marker audit
      run: python scripts/marker-audit

    - name: Selenium tests
      run: |
        coverage run -p -m pytest tests/selenium -vv \
          --run-selenium \
          --run-external-data

    - name: Upload coverage
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: coverage-test-selenium-${{ matrix.python-version }}
        path: .coverage*
        include-hidden-files: true
